name: "DeploySnowFlakeCode"

on:
  workflow_dispatch:

jobs:
  Deploy_Dev:
    uses: swateetjx/Snowflake_CICD_Process/.github/workflows/ReusableDeployEnvironment.yml@main
    with:
      environment: DEV
    secrets: inherit

  Deploy_QA:
    uses: swateetjx/Snowflake_CICD_Process/.github/workflows/ReusableDeployEnvironment.yml@main
    needs: Deploy_Dev
    with:
      environment: QA
    secrets: inherit
